---
- hosts: all
  vars_prompt:
  - name: x
#  - name: y

  tasks:
  - name: "install docker-py"
    pip:
      name: "docker-py"

  - name: "load image"
    docker_image:
       name: "ubuntu"
       tag: 14.04
       load_path: "/media/sf_share/rhel7_5_software_extras/ubuntu-14.04.tar"

  - name: "create container"
    docker_container:
       name: "{{x}}"
       image: "ubuntu:14.04"
       state: "present"
       interactive: true  
 
#  - name: "start container"
#    command: "/usr/bin/docker start mycontainer1"
